### ISSUE TITLE
Design site Navbar

### ISSUE THREAD

**Issue by acmaser12** [csc450ajz/htdocs#1]
Design site navbar that includes site name, proper links, search bar, cart, and account links.

**Comment by xiongj15** [comment]
Just taking a look at old some issues, I believe the design of the Navbar is completed. But the functionality still needs building. Is this issue competed then?

**Comment by zulkiflmohammed** [comment]
I would say the basic design is complete and it is gonna be more of refactoring the design. We will create functionality issue.
