### ISSUE TITLE
Tables not connected in DB (Foreign keys issue)

### ISSUE THREAD

**Issue by acmaser12** [csc450ajz/htdocs#10]
Reported by @zulkiflmohammed 

cartItems, orders table are not connected to product table
ShippingAddress field is not connected to address table

**Comment by acmaser12** [comment]
@zulkiflmohammed When you noticed the issue with the connection between the Order and Product table, what happened? Did values not insert properly?

**Comment by acmaser12** [comment]
Also, @zulkiflmohammed I did not connect the OrderShipAddress to the Address table because this allows users to ship items to addresses other than their account (i.e. to a custom address). What do you think of this?

**Comment by zulkiflmohammed** [comment]
@acmaser12 Sorry for late response, I think you're right about limiting on custom shipping address, we want to keep it simple for now and we wont connect the two tables since we have it connected with the user and the user is connected with order table. So we should be able to get user information.

**Comment by zulkiflmohammed** [comment]
This issue has been solved!
