### ISSUE TITLE
Populate database with sample data

### ISSUE THREAD

**Issue by zulkiflmohammed** [csc450ajz/htdocs#15]

**Comment by acmaser12** [comment]
4 sample users and addresses have been. Adding other sample data later tonight.

**Comment by acmaser12** [comment]
I have added more sample data just now. I will be exporting the db later tonight and will have a copy ready for the whole team to use on localhost.
@zulkiflmohammed 
@xiongj15

**Comment by xiongj15** [comment]
Thanks!

**Comment by acmaser12** [comment]
Updated DB export file has been pushed to the repository. 
@zulkiflmohammed 
@xiongj15
