### ISSUE TITLE
Stored Procedures for different CRUD operations

### ISSUE THREAD

**Issue by zulkiflmohammed** [csc450ajz/htdocs#27]
Here are the lists that I can think of now moving forward that we need for CRUD ops:
@acmaser12 @xiongj15 
- Messages
- Users
- Categories- In addition to general CRUD, we want to get products based on gender...
- User Balance
- Orders
- Product
- Product Review

Feel free to add more...

**Comment by acmaser12** [comment]
So far, the following have been added:
- Perform Transaction
- Delete product
- Add product
- Update product
- Get Products by Seller

**Comment by acmaser12** [comment]
It was decided in Slack that I will implement these as they arise, so let me know here or in Slack if one needs to be added.

**Comment by xiongj15** [comment]
@acmaser12 For the seller page, I created 3 more Procedures. Could you add them when you have the time please. They're all similar to your getCartItems.

![New Proceedures](https://user-images.githubusercontent.com/57078025/77866225-d1dcf100-71f7-11ea-9d46-f1146da950de.png)

**Comment by acmaser12** [comment]
@xiongj15 Can you use the export feature and paste the export here? That is the easiest way for me to add them exactly as you have them.
