### ISSUE TITLE
Create admin page

### ISSUE THREAD

**Issue by acmaser12** [csc450ajz/htdocs#4]
Create landing page for admin, including layout and the various features on the admin page.

**Comment by zulkiflmohammed** [comment]
Hard coded admin page is in progress...

- Home page

- Messaging page

**Comment by acmaser12** [comment]
@zulkiflmohammed What exactly do we have left on this? It might be worth splitting into several different issues.

**Comment by zulkiflmohammed** [comment]
@acmaser12 For the admin pages, all we have so far is a just a hard coded summary page and a little bit of messaging page, This isn’t part of our milestone 2 goal, so I would say it’s an issue that extends all over the class time...

**Comment by zulkiflmohammed** [comment]
Message and User tabs are complete
