### ISSUE TITLE
Figure out/Implement Login procedure

### ISSUE THREAD

**Issue by acmaser12** [csc450ajz/htdocs#9]
Work through how users login and how to check that users are logged in.

**Comment by xiongj15** [comment]
Is this completed In logIn.php CheckAdmin() CheckClient()? Or is that sample code/ idea code?

**Comment by acmaser12** [comment]
Still working on working out the kinks in this... Seems like we are having issues tracking the session variables across pages. Once this is sorted out, all protected pages will be requiring certain login types.

**Comment by acmaser12** [comment]
Login procedure has been fixed. Pages are properly restricted and functioning as expected.
